language: python
python:
  - "3.5"
services:
  - mysql
before_install:
  - mysql -e 'create database pgscm_test;'
install: "pip install -r requirements.txt -r test-requirements.txt"
script: tox -e pep8,cover
notifications:
  email:
    recipients:
      - hieulq19@gmail.com
      - haminhcongbkhn@gmail.com
      - dongha.27995@gmail.com
    on_success: change
on_failure: always